[tool.poetry]
name = "splunk-sdk-games"
version = "0.1.0"
description = ""
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]

packages = [{ include = "*.py" }]

[tool.poetry.dependencies]
python = "^3.9"
# splunk-sdk = {path = "splunk-sdk-python"}
splunk-sdk = "^1.7.4"

[tool.poetry.dev-dependencies]
pytest = "^7.4.4"
pylint = "^3.0.3"
black = "^23.12.1"
mypy = "^1.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "splunk-sdk-games"
version = "0.1.0"
authors = [{ name = "James Hodgkinson", email = "james@terminaloutcomes.com" }]
