[tool.poetry]
name = "splunk-sdk-games"
version = "0.1.0"
description = ""
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]

[tool.poetry.dependencies]
python = "^3.9"
splunk-sdk = "^1.6.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "splunk-sdk-games"
version = "0.1.0"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]
