[tool.poetry]
name = "splunk-sdk-games"
version = "0.1.0"
description = ""
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]

[tool.poetry.dependencies]
python = "^3.9"
splunk-sdk = {path = "splunk-sdk-python"}

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pylint = "^2.12.2"
black = "^22.1.0"
mypy = "^0.931"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "splunk-sdk-games"
version = "0.1.0"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]
